### ISSUE TITLE
this.proxy如何提交form表单呢

### ISSUE THREAD

**Issue by sophiabay** [xiongwilee/koa-grace#11]
如题

**Comment by xiongwilee** [comment]
没明白你的意思，现在的proxy流程是这样的：

`客户端=请求=>Nodejs=代理=>后端（PHP/JAVA）`

无论这里是什么请求(json/form/text/mult)，都会代理给后端，后端捕获请求字段（或者文件流）

**Comment by xiongwilee** [comment]
BTW: 在你的控制器里只需要`yield this.proxy({test:'后端的接口'})`就行，cookie/请求头信息/请求body都会呗带给后端

**Comment by sophiabay** [comment]
嗯嗯，明白了
