### ISSUE TITLE
this.bindDefault方法  在哪里定义的？

### ISSUE THREAD

**Issue by dainixiao** [xiongwilee/koa-grace#12]
this.bindDefault方法  在哪里定义的？我没有找到这个方法~/(ㄒoㄒ)/~~

**Comment by dainixiao** [comment]
还有后台管理的入口在哪里？我也没有找到在哪里

**Comment by xiongwilee** [comment]
`this.bindDefault`方法是在router中间件里注入的，其实就是执行 require('controller/defaultCtrl.js')

**Comment by dainixiao** [comment]
好的  谢谢~
