### ISSUE TITLE
集成mysql吗

### ISSUE THREAD

**Issue by gatspy** [xiongwilee/koa-grace#14]
想集成mysql，能推荐下吗

**Comment by xiongwilee** [comment]
koa-grace暂时只支持session(redis存储)和简单mongo database方案， 如果想集成mysql的话可以自己用[co-mysql](https://github.com/coderhaoxin/co-mysql)封装中间件

**Comment by gatspy** [comment]
@xiongwilee 谢谢啊。最近做的项目准备使用grace。

**Comment by xiongwilee** [comment]
cool

**Comment by gatspy** [comment]
@xiongwilee 请教个问题，基于angular的spa怎么和grace整合呢？app目录结构中是不是只需要controller呢？

**Comment by xiongwilee** [comment]
一个个回答：

**Comment by xiongwilee** [comment]
一个个回答：
1、基于angular的spa怎么和grace整合呢？
基于angular的spa和grace整合你可以参考下我们团队基于vue的一个boilerplate : [grace-vue-webpack-boilerplate](https://github.com/Thunf/grace-vue-webpack-boilerplate) ，这个boilerplate做的事情就是用webpack把.vue的文件编译到static目录；

2、app目录结构中是不是只需要controller呢？
不是。除了生成Nodejs页面路由，你可能还需要ajax （通过proxy实现即可），另外你还需要一个模板（spa可能只需要一个.html模板文件）放在views目录下即可，还有需要angular的静态文件。

3、怎么serve spa静态文件？
grace自带静态文件server，将静态文件放在static目录下即可，访问路径就是`http://domain:port/moduleName/static/*`,参考`app/demo/static`和koa-grace-static中间件；**推荐在生产环境使用Nginx做static server **

**Comment by gatspy** [comment]
@xiongwilee 谢谢您的及时详尽的答复啊。这下信心大多了。

**Comment by xiongwilee** [comment]
客气了，有问题随时问；我们团队现在正在用，线上好几亿的目标全是grace扛着的 哈哈

**Comment by gatspy** [comment]
@xiongwilee  又要麻烦您了，没有接触过`webpack`啊。`grace-vue-webpack-boilerplate` clone以后`npm run build` 。 这个项目build以后是直接把`server/app/`中的`grace_boilerplate`拷贝到`koa-grace/app`里面吗？ vhost配置需要修改吗？

**Comment by xiongwilee** [comment]
对，host不需要改，现在我们的目录结构是这样的：
```
fe
├── app
├── build
└── server(就是koa-grace)
```
开发的时候启动watch 把app里的文件编译之后拷贝到server目录下的app， 如果不想用这种方式的话，可以直接就在server里开发的
