### ISSUE TITLE
关于vhost: '127.0.0.1/test':'demo_test'

### ISSUE THREAD

**Issue by vance-liu** [xiongwilee/koa-grace#17]
首先，非常感谢你提供这么棒的项目！
对于vhost有点疑问，如果这么配置'127.0.0.1':'blog'，不会出现问题，现在我配置'127.0.0.1/other':'other'，但是 127.0.0.1:3000/other 无法访问。
再解释下就是，希望127.0.0.1:3000访问blog项目，通过127.0.0.1:3000/other访问other项目。
还有就是能不能贴一下你的blog的配置呢？

**Comment by xiongwilee** [comment]
你是用的v2.x版本吧？
刚刚加了一个示例：
参考`config/main.development.js`:
````
  vhost: {
    '127.0.0.1': 'demo',
    'localhost': 'blog',
    'feclub.cn': 'blog',
    'localhost/test': 'test'
  },
````
访问：`localhost:3000/test`指向`test`项目，其他的都会指向`blog`项目

**Comment by xiongwilee** [comment]
你是用的v2.x版本吧？
刚刚加了一个示例：
参考`config/main.development.js`:
````
  vhost: {
    '127.0.0.1': 'demo',
    'localhost': 'blog',
    'feclub.cn': 'blog',
    'localhost/test': 'test'
  },
````
访问：`localhost:3000/test`指向`test`项目，其他的都会指向`blog`项目

**Comment by vance-liu** [comment]
貌似不行呢，访问localhost:3000/test，显示not fund，我删除localhost:3000:blog，再修改为localhost:3000/blog:blog，还是不行呢，是我姿势不对？

**Comment by vance-liu** [comment]
貌似不行呢，访问localhost:3000/test，显示not fund，我删除localhost:blog，再把localhost/test:test修改为localhost/blog:blog，还是不行呢，是我姿势不对？

**Comment by xiongwilee** [comment]
应该是访问：`localhost:3000/test/`或者`localhost:3000/test/*`才行哈 , 如果只有`/test`是不会匹配到子模块的

**Comment by vance-liu** [comment]
@xiongwilee 没用啊，还是Not Found！你那边可以么？

**Comment by xiongwilee** [comment]
打log看下吧，子模块匹配的源码在这里，很简单：https://github.com/xiongwilee/koa-grace/blob/v2.x/middleware/vhost/index.js#L51-L75

**Comment by vance-liu** [comment]
现在是这样，app下面有两个一样的demo项目名字分别是demo和demo2，访问localhost:3000能正常访问到demo项目，调试信息如下：
![image](https://cloud.githubusercontent.com/assets/9456694/20911524/740c4cf0-bba3-11e6-9d8d-0fc0ce507d64.png)
但是访问localhost:3000/demo2/，就是Not Found！访问localhost:3000/demo2/*也是一样的，调试信息如下：
![image](https://cloud.githubusercontent.com/assets/9456694/20911488/3e4b000c-bba3-11e6-8d2b-e5930f69f9b5.png)
我的环境是node v5.12.0

**Comment by xiongwilee** [comment]
这个应该是走到了子模块 ，但是你的子模块下找不到文件，所以返回`Not found!`；你把你demo2的目录结构和index.js文件内容贴出来看看？

**Comment by vance-liu** [comment]
demo项目就是koa-grace原来的demo！

**Comment by xiongwilee** [comment]
![](https://raw.githubusercontent.com/xiongwilee/demo/master/photo/QQ20161206-151617.jpg)  ， 确定地址没有问题？

**Comment by vance-liu** [comment]
我看明白是什么意思了，重新克隆了项目修改了下，app目录如下
![image](https://cloud.githubusercontent.com/assets/9456694/20917438/831f90ca-bbcc-11e6-89b6-08b87b5ddfd7.png)
非常感谢你，之前遇到的问题是子目录找不到的问题，现在重新测试了下test，访问localhost:3000/test/index可以运行，目录指向test=》controller=》test=》index.js下，默认为index方法，访问localhost:3000/test/index/index也是可以的！现在想问下，我如何能路由到hello=》controller=》home.js呢？

**Comment by xiongwilee** [comment]
没明白你的意思，可以加我微信： ![](https://raw.githubusercontent.com/xiongwilee/demo/master/photo/wechat.jpg)

**Comment by vance-liu** [comment]
非常nice的项目，希望尽快升级^v^

**Comment by xiongwilee** [comment]
DONE 。
参考配置：https://github.com/xiongwilee/koa-grace/blob/v2.x/config/main.development.js#L17-L22
然后就可以生成子模块顶级路由：https://github.com/xiongwilee/koa-grace/blob/v2.x/app/test/controller/home.js#L2-L6
