### ISSUE TITLE
nice。。。

### ISSUE THREAD

**Issue by yuu2lee4** [xiongwilee/koa-grace#2]
// mongo configuration
mongo: {
  'blog': 'mongodb://localhost:27017/blog'
}

但是这个  现在应该是
mongo: {
  'api': 'mongodb://localhost:27017/blog'
}
吧？别忘了更新文档 `(*∩_∩*)′

还有  访问127.0.0.1:3000  直接404了

话说啥时候升级到koa2呢

**Comment by xiongwilee** [comment]
好多问题~~

**Comment by xiongwilee** [comment]
好多问题。。。
1. 第一个配置是`blog:'mongodb://localhost:27017/blog'`，你可以根据自己的需要配置；（不过：koa-grace本身是前后端分离框架，这里集成的mongoose的功能其实也是不够完善，别提数据库分库分表、主从分离、消息队列一堆功能了；不过你可以在自己的博客里使用完全没有问题）;
2. 127.0.0.1:3000 404确实是在windows下面的一个BUG，现在已经修复了;
3. koa-grace会跟koa同步更新。至于针对koa2的升级，目前没有打算，直到Nodejs默认支持了async/await语法之后，参考： [https://github.com/koajs/koa/issues/533](https://github.com/koajs/koa/issues/533);
