### ISSUE TITLE
了解一下koa-grace目前的状态

### ISSUE THREAD

**Issue by shipengyan** [xiongwilee/koa-grace#20]
- 在生产上使用么？
- 使用量有多大？

3ks

**Comment by xiongwilee** [comment]
在用，例如：
* [qd.qufenqi.com](qd.qufenqi.com)
* [m.qufenqi.com](m.qufenqi.com)
* 其他内网业务

目前是：6台8核机器，承载约500TPS的业务；配合Varnish，双十一峰值2000TPS也没有问题
