### ISSUE TITLE
路由的问题

### ISSUE THREAD

**Issue by sg513017** [xiongwilee/koa-grace#21]
我在用你这个框架的时候遇到个路由的问题，现在设计两个api，
1. /api/topup  方法是get
2. /api/topup/:id, 方法是post
请问我该怎么在Controller里写这个路由呢？

**Comment by xiongwilee** [comment]
现在的路由方案是默认get和post都支持的

**Comment by sg513017** [comment]
我是这样写的：在api.js里写的
exports.topup = function(){}
extports.topup.__regular__ ='/:id',
下面定义的规则是不是只有/api/topup/:id这样访问才可以？

我疑惑的是如果定义了regular, 那/api/topup这个api又该如何响应处理呢？

请帮我解惑，谢谢

**Comment by xiongwilee** [comment]
```
exports.topup = function(){}
extports.topup.__regular__ ='/:id',
```
这样的话，会生成两类路由 `/api/topup/:id`及`/api/topup`；可以根据有没有`this.param.id`这个字段来判断是哪一类

**Comment by sg513017** [comment]
解决了， 谢谢！
