### ISSUE TITLE
访问不了hello/koagracce

### ISSUE THREAD

**Issue by yuu2lee4** [xiongwilee/koa-grace#3]
exports.koagrace = funtion* (){
  this.body = 'hello koa-grace！';
}
 function单词拼错了

访问 http://127.0.0.1:3000/hello/koagrace  404

**Comment by xiongwilee** [comment]
这是哪个文件的拼写报错呢？

**Comment by yuu2lee4** [comment]
3.2.3 控制器
就是这一章节

现在我访问127.0.0.1:3000/home   http://127.0.0.1:3000/hello/koagrace 全是404啊  难道是我win的原因？

**Comment by xiongwilee** [comment]
呃，是的；
是在windows下面的一个BUG，现在已经修复了，你可以更新下koa-grace然后npm install下之后再试试哈

**Comment by yuu2lee4** [comment]
嗯 好的。。。

**Comment by xiongwilee** [comment]
拼写错误也更正了，THX ~
