### ISSUE TITLE
Nunjucks自定义选项不起作用

### ISSUE THREAD

**Issue by haizhilin2013** [xiongwilee/koa-grace#35]
###  Nunjucks自定义选项不起作用, 是以下这个文件缺少了配置项引起的
> node_modules\grace-consolidate\lib\consolidate.js（1119行）

要将

`if (options.settings && options.settings.views) engine.configure(options.settings.views);`

修改为：

`if (options.settings && options.settings.views) engine.configure(options.settings.views, options.settings.options);`

**Comment by xiongwilee** [comment]
开了个分支完美支持nunjuck，https://github.com/xiongwilee/koa-grace/tree/nunjucks
