### ISSUE TITLE
路由可以使用别的模式

### ISSUE THREAD

**Issue by haizhilin2013** [xiongwilee/koa-grace#36]
# 路由可以使用别的模式
> 要针对SEO做优化，路由要添加.html后缀，不知道要怎么弄，如：www.xxxx.com/user/index.html  这样子的

**Comment by xiongwilee** [comment]
DONE: https://github.com/xiongwilee/koa-grace/commit/c85ff76ebb3e1080d294c193e7dbf11c579fc343
