### ISSUE TITLE
多个post请求且有不同的form参数时，有好的解决方案吗？

### ISSUE THREAD

**Issue by haizhilin2013** [xiongwilee/koa-grace#37]
### 多个post请求并且都有不同的form参数时，有好的解决方案吗？
> 一个页面有好多post请求，一个个写感觉不美观，能整合到proxy里吗？是要修改proxy中间件了吧

**Comment by xiongwilee** [comment]
可以在`onBeforeRequest`钩子里实现：https://github.com/xiongwilee/koa-grace/commit/a7fa0ff75afda73c19d3fa8e27c48a44c4264b90

**Comment by xiongwilee** [comment]
可以在`onBeforeRequest`钩子里实现：https://github.com/xiongwilee/koa-grace/commit/a7fa0ff75afda73c19d3fa8e27c48a44c4264b90
