### ISSUE TITLE
controller下面必须得有defaultCtrl.js这点没有说明

### ISSUE THREAD

**Issue by yuu2lee4** [xiongwilee/koa-grace#4]
controller下面必须得有defaultCtrl.js这点没有说明！
你的微信或者qq是多少啊  或者整个论坛 qq群什么的  可以交流讨论

**Comment by xiongwilee** [comment]
好问题。
1、我升级下配置，支持不需要defaultCtrl.js
2、不应该啊，this.mongo在`koa-grace-mongo`里是默认注入了的 ， 给我看下日志？

微信 & QQ: 373071372 , 目前还没有弄社区呢，可以搞一个 哈哈

**Comment by yuu2lee4** [comment]
第二个问题 我已经解决了 原来是我没写数据库的配置

**Comment by xiongwilee** [comment]
第一个问题修复了，如果没有defaultCtrl.js文件但是调用了`this.bindDefault()`话只会提示`Cannot find default controller './example/controller/defaultCtrl.js'` 而不会crash

**Comment by dainixiao** [comment]
bindDefault在哪里定义的这个方法  我怎么没有找到呢~

**Comment by xiongwilee** [comment]
你自己定义即可，参考：`app/demo/controller/defaultCtrl.js` , 在controller里`yield this.bindDefault()` 就行
