### ISSUE TITLE
配置mongoDB配置路径

### ISSUE THREAD

**Issue by ifany** [xiongwilee/koa-grace#5]
你好，如文档中所说：

修改配置项：config.mongo.blog 为您的本地mongoDB的路径:
// mongo configuration mongo: { 'blog': 'mongodb://localhost:27017/blog' }

---

我的mongoDB安装路径如下：
C:\Program Files\MongoDB
C:\Program Files\MongoDB\Server\3.2\bin

 { 'blog': 'mongodb:**_' }，**_这里的路径需要怎么填？

**Comment by xiongwilee** [comment]
这里要配置的是mongo server的uri， 你可以使用默认配置`mongodb://localhost:27017/blog`；、
另外，得提一点，mongo server只是koa-grace附加的，勉强能用的功能而已（koa-grace的本质是前后端分离server）；如果不想玩数据库，不配置也没问题~

**Comment by xiongwilee** [comment]
Hi ifany, 
这里要配置的是mongo server的uri， 你可以使用默认配置mongodb://localhost:27017/blog；、
另外，得提一点，mongo server只是koa-grace附加的，勉强能用的功能而已（koa-grace的本质是前后端分离server）；如果不想玩数据库，不配置也没问题~
