### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by nieyulin112** [xiongwilee/koa-grace#6]
@xiongwilee :你好！
// mongo配置
  mongo: {
    options: {
      // mongoose 配置
    },
    api: {
      'blog': 'mongodb://localhost:27017/blog'
    }
  }
这个配置的意思，可以理解为blog是数据库的库名，对吧？

**Comment by nieyulin112** [comment]
@xiongwilee 
对应数据库里面的几张表和表的结构可以说一下吗？
谢谢！

**Comment by xiongwilee** [comment]
@nieyulin112 
对，`blog`就是数据库的库名；你可以参考`app/blog`下的`model/mongo/*`的案例，就一目了然了！
不过还是建议不要在生产环境使用mongoose的功能，不过用来写一个博客还是绰绰有余的哈
