### ISSUE TITLE
关于main.production.js 49行path配置问题

### ISSUE THREAD

**Issue by yan-jie** [xiongwilee/koa-grace#7]
如题目描述，我觉得该行配置应该是  ./app
代码里路径为  ../app 
不知是否为我理解错误

**Comment by xiongwilee** [comment]
哈哈 ，赞仔细！
不过在生产环境的配置 `main.production.js` 里的path确实是`../app`，主要是为了在生产环境下将`app`抽离出来，避免git仓储的冲突和npm包管理的冲突~

**Comment by yan-jie** [comment]
我是刚刚在本地测试生产环境时，项目没报错，但一直访问不了，也没日志的情况下，debug找到的。
我大概理解你的意思，谢谢

**Comment by xiongwilee** [comment]
是的，生产环境只开放了error日志，另外我们的生产环境下其实有一个access日志的中间件的；暂时还没有在开源版本里引用进来。
