### ISSUE TITLE
github oauth 配置问题

### ISSUE THREAD

**Issue by playedclass** [xiongwilee/koa-grace#8]
源码里的 回调URL填的是网站的，不能用，自己申请的，授权都不成功，回调URL是有什么格式吗
message: "Not Found"

**Comment by xiongwilee** [comment]
你是在开发环境下吗？有可能是缺一个API配置(开发环境下只有github:'https://github.com/')：
```
  // controller中请求各类数据前缀和域名的键值对
  api: {
    github_api: 'https://api.github.com/',
    github: 'https://github.com/',
  },
```

**Comment by playedclass** [comment]
`oauthInfo: {
error: "bad_verification_code",
error_description: "The code passed is incorrect or expired.",
error_uri: "https://developer.github.com/v3/oauth/#bad-verification-code"
}`
最后是跳转到http://feclub.cn/user/oauth?，我是用本地开发环境运行的，改了main.development.js的内容还是这个问题

**Comment by playedclass** [comment]
换成自己的，可以了，谢了

**Comment by xiongwilee** [comment]
cool
